version: '3.7'

services:
  nginx:
    container_name: nginx
    image: nginx:mainline-alpine3.18-slim
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    expose:
      - "80"
    networks:
      - prometheus-network
    volumes:
      - ${NGINX_CONF_DIR}:/etc/nginx/nginx.conf
      - ${NGINX_LOG_DIR}:/var/log/nginx/
    depends_on:
      - grafana
      - prometheus
    
  grafana:
    container_name: grafana
    image: grafana/grafana:main
    restart: unless-stopped
    networks:
      - prometheus-network
    ports:
      - "3000:3000"
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_SERVER_ROOT_URL=https://localhost/grafana
      - DS_PROMETHEUS=prometheus
    volumes: 
      - ./grafana/:/var/lib/grafana
    privileged: true
    depends_on:
      - prometheus

  prometheus:
    container_name: prometheus
    image: prom/prometheus:main
    restart: unless-stopped
    networks:
      - prometheus-network
    ports:
      - "9090:9090"
    volumes: 
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    privileged: true

  vector:
    container_name: vector
    image: timberio/vector:0.30.0-debian
    restart: unless-stopped
    networks:
      - prometheus-network
    ports:
      - "8080:8080"
    volumes:
      - ${NGINX_LOG_DIR}:/var/log/nginx
      - ${VECTOR_CONF_DIR}:/etc/vector/vector.toml
    depends_on:
      - prometheus

networks:
  prometheus-network:
    driver: bridge
