global:
  scrape_interval: 5s
  evaluation_interval: 5s
  
scrape_configs:
  - job_name: "prometheus"
    # metrics_path defaults to '/metrics'
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "vector"
    static_configs:
      - targets: ["vector:8080"]
